runtime: go
api_version: go1.8

handlers:
- url: /.*
  script: _go_app

nobuild_files:
- vendor

skip_files:
- .*vendor

includes:
- secret.yaml

instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
